apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    app.openshift.io/vcs-ref: ""
    app.openshift.io/vcs-uri: https://github.com/0penshifty/troubleshooting.git
    openshift.io/generated-by: OpenShiftWebConsole
  labels:
    app: troubleshooting
    app.kubernetes.io/component: troubleshooting
    app.kubernetes.io/instance: troubleshooting
    app.kubernetes.io/name: troubleshooting
    app.kubernetes.io/part-of: troubleshoot
  name: troubleshooting
spec:
  lookupPolicy:
    local: false
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    app.openshift.io/vcs-ref: ""
    app.openshift.io/vcs-uri: https://github.com/0penshifty/troubleshooting.git
    openshift.io/generated-by: OpenShiftWebConsole
  labels:
    app: troubleshooting
    app.kubernetes.io/component: troubleshooting
    app.kubernetes.io/instance: troubleshooting
    app.kubernetes.io/name: troubleshooting
    app.kubernetes.io/part-of: troubleshoot
  name: troubleshooting
spec:
  failedBuildsHistoryLimit: 0
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: troubleshooting:latest
  runPolicy: Serial
  source:
    contextDir: /
    git:
      uri: https://github.com/0penshifty/troubleshooting.git
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
    type: Docker
  successfulBuildsHistoryLimit: 0
  triggers:
  - generic:
      secretReference:
        name: troubleshooting-generic-webhook-secret
    type: Generic
  - github:
      secretReference:
        name: troubleshooting-github-webhook-secret
    type: GitHub
  - type: ConfigChange
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    app.openshift.io/route-disabled: "false"
    app.openshift.io/vcs-ref: ""
    app.openshift.io/vcs-uri: https://github.com/0penshifty/troubleshooting.git
    openshift.io/generated-by: OpenShiftWebConsole
  labels:
    app: troubleshooting
    app.kubernetes.io/component: troubleshooting
    app.kubernetes.io/instance: troubleshooting
    app.kubernetes.io/name: troubleshooting
    app.kubernetes.io/part-of: troubleshoot
  name: troubleshooting
spec:
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    app: troubleshooting
    deploymentconfig: troubleshooting
  strategy:
    activeDeadlineSeconds: 21600
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: troubleshooting
        deploymentconfig: troubleshooting
    spec:
      containers:
      - image: troubleshooting:latest
        imagePullPolicy: Always
        name: troubleshooting
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - troubleshooting
      from:
        kind: ImageStreamTag
        name: troubleshooting:latest
      lastTriggeredImage: troubleshooting:latest
    type: ImageChange
  - type: ConfigChange
